version: '3.9'
services:
  backend:
    build:
      context: ./backend
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    command: npm run dev -- --host 0.0.0.0 --port 5173
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: development
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: 
